#!/usr/bin/python3
class colo:
    HEADER = '\033[95m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    UNDERLINE = '\033[4m'
    RED='\033[1;31m'
    GREEN='\033[1;32m'
    CYAN='\033[1;36m'
    NC='\033[0m'
    BOLD='\033[1;37m'
    YELLOW='\033[1;33m'

import json
import sys
import webbrowser
import os

def VOJOpen(task):
    task = task.upper()
    if(task.endswith('.cpp')):
        task = task[:-4]

    try:
        inp = problemname[task].split(',')
    except:
        print('%shey u sure the problem exists?%s' % (colo.RED, colo.NC))
        exit(0)

    if len(inp) == 1:
        loadProblem(inp[0], 0)
    else:
        print('%sThere are several contests to submit to this problem:%s' % (colo.YELLOW, colo.NC))
        id = 1

        for probs in inp:
            contest = probs.split('/')[0]
            print('>>> (%d) %s' % (id, contests[contest]))
            id += 1

        option = int(input('%sChoose one: %s' % (colo.YELLOW, colo.NC)))
        if 1 > option or option > len(inp):
            print('%sInvalid option.\nQuitting...%s' % (colo.RED, colo.NC))
            exit(0)
        else:
            loadProblem(inp[option - 1], 0)

def loadProblem(s, status):
    contestId = s.split('/')[0]
    problemLetter = s.split('/')[1]
    print('%sLoading contest %s, problem %s...%s' % (colo.RED, contests[contestId], task, colo.NC))

    try:
        if status == 0:
            webbrowser.open('https://codeforces.com/group/FLVn1Sc504/contest/%s/problem/%s' % (contestId, problemLetter))
        elif status == 1:
            submitlink = 'https://codeforces.com/group/FLVn1Sc504/contest/%s/problem/%s' % (contestId, problemLetter)
            os.system('cf submit %s' % (submitlink))
        else:
            raise Exception()
    except:
        print('%sError.%s' % (colo.RED, colo.NC))
        exit(0)

    print('%sDone.%s' % (colo.GREEN, colo.NC))

def VOJSubmit(file):
    file = file.upper()
    task = file
    if(file.endswith('.cpp')):
        task = file[:-4]

    print('%sSubmitting for problem: %s%s' % (colo.CYAN, task, colo.NC))
    try:
        inp = problemname[task].split(',')
    except:
        print('%shey u sure the problem exists?%s' % (colo.RED, colo.NC))
        exit(0)

    if len(inp) == 1:
        loadProblem(inp[0], 1)
    else:
        print('%sThere are several contests to submit this problem:%s' % (colo.YELLOW, colo.NC))
        id = 1

        for probs in inp:
            contest = probs.split('/')[0]
            print('>>> (%d) %s' % (id, contests[contest]))
            id += 1

        option = int(input('%sChoose one: %s' % (colo.YELLOW, colo.NC)))
        if 1 > option or option > len(inp):
            print('%sInvalid option.\nQuitting...%s' % (colo.RED, colo.NC))
            exit(0)
        else:
            loadProblem(inp[option - 1], 1)

# ==========================================================

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print('%sNot enough arguments.%s' % (colo.RED, colo.NC))
        exit(0)

    with open('/home/hikarii/.local/bin/VOJData/links.json', 'r') as f:
        problemname = json.load(f)

    with open('/home/hikarii/.local/bin/VOJData/contest_name.json', 'r') as f:
        contests = json.load(f)

    file = sys.argv[1].upper()
    task = file
    if(file.endswith('.cpp')):
        task = file[:-4]

    if sys.argv[1] == 'open':
        VOJOpen(sys.argv[2])
    elif sys.argv[1] == 'submit':
        VOJSubmit(sys.argv[2])
    elif sys.argv[1] == 'help' or sys.argv[1] == 'h':
        print('%svoj open [problem name]' % colo.CYAN)
        print('voj submit [problem name]%s' % colo.NC)
    else:
        print('%shey u sure the parameter (open/submit) is correct?%s' % (colo.RED, colo.NC))


